export const CREATE_COURSE = 'CREATE_COURSE';
export const LOAD_COURSES_OK = 'LOAD_COURSES_OK';
export const CREATE_COURSES_OK = 'CREATE_COURSES_OK';
export const UPDATE_COURSES_OK = 'UPDATE_COURSES_OK';

export const LOAD_AUTHORS_OK = 'LOAD_AUTHORS_OK';
